### ISSUE TITLE
Pickle load issue -> nan loss 

### ISSUE THREAD

**Issue by Arkkienkeli** [TheMatrixMaster/omics-guided-gfn#1]
Hi, very nice work, very interesting utilization of PUMA dataset :+1: 
I am trying to run the code like in ReadMe: `python gflownet/src/gflownet/tasks/morph_frag.py `  with `mmc_proxy` and I tried a couple of samples, though I hit a couple of issues:
First, if I start the code as is I get an error:
```
AttributeError: module 'multimodal_contrastive.networks.components' has no attribute 'GNEpropGIN'
```
after, I renamed `MoleculeEncoder` in `multimodal_contrastive.networks.components` to `GNEpropGIN` (and in the corresponding `gmc_sm.yaml` config as well). After that change I get:
```
Traceback (most recent call last):
  File "/omics-guided-gfn/gflownet/src/gflownet/trainer.py", line 223, in train_batch
    loss, info = self.algo.compute_batch_losses(self.model, self.critic1, self.critic2,
  File "/omics-guided-gfn/gflownet/src/gflownet/algo/soft_actor_critic.py", line 260, in compute_batch_losses
    raise ValueError("loss is not finite")
ValueError: loss is not finite
```
 
Thank you!

**Comment by thematrixmaster** [comment]
Hi @Arkkienkeli, thanks for your interest in our work and for helping identify these issues. I've gone in and fixed some of the things you mentioned and it should hopefully work ok now. Can you give it another try and let me know if anything isn't resolved?

**Comment by Arkkienkeli** [comment]
Yes, it starts now, thank you!
